// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7a7GxVnJoibz7VGmIy_edNHrAv5QN52I',
    appId: '1:715835989881:web:6d73354c93b579827359a8',
    messagingSenderId: '715835989881',
    projectId: 'smartsave-ai-5fed2',
    authDomain: 'smartsave-ai-5fed2.firebaseapp.com',
    storageBucket: 'smartsave-ai-5fed2.firebasestorage.app',
    measurementId: 'G-2QY7S15HK0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAr9Cf0HVQgVsvHRAkcQ25eol3mRmyDJ2g',
    appId: '1:715835989881:android:69173f9d8679adf87359a8',
    messagingSenderId: '715835989881',
    projectId: 'smartsave-ai-5fed2',
    storageBucket: 'smartsave-ai-5fed2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDg09YxxJADWYNTDpqx53wq_UMNtAZ8eW4',
    appId: '1:715835989881:ios:ac0c9884be3d4a0c7359a8',
    messagingSenderId: '715835989881',
    projectId: 'smartsave-ai-5fed2',
    storageBucket: 'smartsave-ai-5fed2.firebasestorage.app',
    iosBundleId: 'com.example.smartsaveAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDg09YxxJADWYNTDpqx53wq_UMNtAZ8eW4',
    appId: '1:715835989881:ios:ac0c9884be3d4a0c7359a8',
    messagingSenderId: '715835989881',
    projectId: 'smartsave-ai-5fed2',
    storageBucket: 'smartsave-ai-5fed2.firebasestorage.app',
    iosBundleId: 'com.example.smartsaveAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7a7GxVnJoibz7VGmIy_edNHrAv5QN52I',
    appId: '1:715835989881:web:38c0541f036a48297359a8',
    messagingSenderId: '715835989881',
    projectId: 'smartsave-ai-5fed2',
    authDomain: 'smartsave-ai-5fed2.firebaseapp.com',
    storageBucket: 'smartsave-ai-5fed2.firebasestorage.app',
    measurementId: 'G-73X45YQBRR',
  );
}
